[package]
name = "CW-20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm = "0.7.2"
cosmwasm-std = "1.2.1"
schemars = "0.8.12"
cw20 = "1.0.1"
cosmwasm-storage = "1.2.1"
serde = "1.0.152"